# Generated by Django 2.2 on 2021-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='about',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='job',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
